name: home_decor
description: "A simple home decor Flutter app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  google_fonts: ^6.3.2
  cached_network_image: ^3.4.1
  animations: ^2.1.0
  firebase_core: ^3.8.1
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.5.0
  provider: ^6.1.2
  intl: ^0.20.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  firebase_storage: ^12.4.10
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
